# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://docs.astronomer.io/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: kafka_synapce
      conn_type: general
      conn_extra:
        bootstrap.servers: kafka:19092
        group.id: group_1
        security.protocol: PLAINTEXT
        enable.auto.commit: False
        auto.offset.reset: "beginning"
    - conn_id: kafka_listener
      conn_type: general
      conn_extra:
        bootstrap.servers: kafka:19092
        group.id: group_2
        security.protocol: PLAINTEXT
        enable.auto.commit: False
        auto.offset.reset: "beginning"
    # Дополнительный коннекшен (дублирующий тот, что создается через init-kap-db)
    - conn_id: kap_247_db
      conn_type: postgres
      conn_host: kap_247_db
      conn_login: kap_user
      conn_password: kap_password
      conn_schema: kap_data
      conn_port: 5432
